#!/usr/bin/env bash

read -p "Enter input file name: " input # Gets input file
if [[ -f "$input" ]] # Checks if input file exists
then
  if [[ -r "$input" ]] # Checks if input file is readable
  then
    read -p "Enter output file name: " output # Gets output file
    if [[ -f "$output" ]] # Checks if output file exists
    then
      if [[ -w "$output" ]] # Checks if output file is writable
      then
        echo "File '$output' exists." # Outputs message indicating file exists
        read -p "Append to it (y/n)? " choice # Gets choice from user
        while [ "$choice" != "y" ] && [ "$choice" != "Y" ] && [ "$choice" != "n" ] && [ "$choice" != "N" ] # Loops until one of the option is chosen
        do
          echo "Invalid option" # Error message
          read -p "Append to it (y/n)? " choice # Message is repeated
        done
        if [[ "$choice" = "y" ]] || [[ "$choice" = "Y" ]] # If yes is entered
        then
          while IFS='' read -r line # Reads file
          do
            echo $line >> $output # Outputs line to output file
            echo "" >> $output # Outputs empty line for double space
          done < "$input" # End of file reading
        elif [[ "$choice" = "n" ]] || [[ "$choice" = "N" ]] # If no is entered
        then
          exit 1 # Exits program
        fi
      else
        echo "File '$output' is not writable." # Message indicating file is not writable
      fi
    else
      touch $output # If output file does not exists, it creates one
    fi
  else
    echo "File '$input' is not readable." # Indicates file is not readable
  fi
else
  echo "File '$input' does not exist." # Indicates file does not exist
fi
