#!/usr/bin/env bash

read -p "Enter input file name: " file  # Gets input file
if [[ -f "$file" ]] # Checks if file exists
then
  if [[ -r "$file" ]] # Checks if file is readable
  then
    read -p "Enter the word to search for: " word # Gets word to search for
    read -p "Case-sensitive (y/n)? " case # Gets type of case
    while [ "$case" != "y" ] && [ "$case" != "Y" ] && [ "$case" != "n" ] && [ "$case" != "N" ] # Loops until user enters yes or no
    do
      echo "Invalid option" # Error message
      read -p "Case-sensitive (y/n)? " case # Message is repeated
    done
    if [[ "$case" = "y" ]] || [[ "$case" = "Y" ]] # If user enters yes
    then
      found=$(grep "$word" "$file") # Searches word in file
    elif [[ "$case" = "n" ]] || [[ "$case" = "N" ]] # If user enters no
    then
      found=$(grep -i "$word" "$file") # Searches for word in file
    fi
    if [[ -n "$found" ]] # Checks if the word is found in the file
    then
      echo "$found" # Outputs the matching words
    else
      echo "Word '$word' not found." # Otherwise, message is thrown indicating word is not found
    fi
  else
    echo "File '$file' is not readable." # Indicates that the file is not readable
  fi
else
  echo "File '$file' does not exist." # Indicates that the file does not exist
fi
